### ISSUE TITLE
升级 img4ye 需要做的调研

### ISSUE THREAD

**Issue by fushang318** [mindpin/image-service#17]
### 如何收费

http://kb.qiniu.com/571tr2gn
http://www.qiniu.com/pricing

### 绑定域名

使用自定义域名的要求是
1 必须是标准用户（手机+邮箱+身份认证 信息验证）
认证分为个人认证和企业认证(我注册的账号，提交个人认证只等待了两个小时就通过了)

2 账户余额大于10元可用

### UploadToken

其实这是唯一的上传模式，无论是以下哪种上传流程

1 浏览器 -> img4ye 服务器 -> 七牛云存储

2 浏览器 -> 七牛云存储  -> 发送创建成功的信息给 img4ye 服务器

3 浏览器 -> 七牛云存储 -> 浏览器 -> 发送创建成功的信息给 img4ye 服务器

都需要 UploadToken

另外七牛官网文档中提到可以支持跨域上传
理论上跨域和UploadToken结合的话，可以支持浏览器直接上传文件到七牛云存储（支持整个文件上传和分段上传），而不经过 img4ye 服务器中转

跨域相关说明：
http://developer.qiniu.com/docs/v6/api/overview/security.html
![](http://img.teamkn.com/i/ROo5WNl1.png)

### 获取图片平均颜色值

这个API 七牛是有的
http://developer.qiniu.com/docs/v6/api/reference/fop/image/imageave.html

### 开发SDK

七牛自己写了 Ruby SDK，可以使用
http://developer.qiniu.com/docs/v6/sdk/ruby-sdk.html

七牛自己写了 JavaScript SDK，可以使用
http://developer.qiniu.com/docs/v6/sdk/javascript-sdk.html

### 用到的功能

1 上传读取云存储图片的核心逻辑
2 匿名上传
3 微博用户上传
4 匿名自定义尺寸设置
5 微博用户自定义尺寸设置
6 支持 短网址服务 生成缩略图上传的API
7 微博登陆

### 没有用到的功能

1 个人用户使用空间统计
2 图片增加 tag
3 用户邀请机制
4 QQ登陆
5 github登陆

### 迁移到 rails 需要做的事情

暂时没有想到什么坑

### 迁移到 七牛 需要做的事情

1 新的逻辑需要可以读取旧的aliyun数据
2 新的逻辑需要可以读取写入新的qiniu数据

所以 images 需要加字段来支持以上逻辑

**Comment by ben7th** [comment]
修改为 rails 工程之后，保留的和去掉的特性

保留的：

1. 云存储核心逻辑（改用七牛云存储实现）
2. 匿名上传
3. 登录后用户上传
4. 登录后用户自定尺寸配置
5. 用于支持短网址二维码生成服务的 API
6. 微博登录
7. 个人用户使用空间统计
8. QQ登录和github登录的逻辑先保留

-------------

去掉的：
1. 匿名用户自定义尺寸，不要了。
2. 图片增加tag，UI方面没有设计过，不要了。以后要再加。
3. 用户邀请机制，先不要了。

------------

基于以上考量，在需求梳理完毕（包括 mockup 就绪，一些流程图就绪）的情况下，择日用 rails 工程进行重构实现。

**Comment by ben7th** [comment]
已经集成到 0.3 版。
