### ISSUE TITLE
个人使用情况汇总逻辑

### ISSUE THREAD

**Issue by destinyd** [mindpin/image-service#20]
个人使用情况汇总逻辑（已上传图片数统计，已使用空间统计，尺寸配置数统计）

**Comment by destinyd** [comment]
```
李飞  12:29:34
这个回调你写在 SpaceState 类的单独 module 里吧
```

**Comment by destinyd** [comment]
SpaceState 打算作为concern，记录在user里，并实现重新统计方法

**Comment by destinyd** [comment]
···ruby
# 已上传图片总数
user.images.count # 3784

# 尺寸配置总数
user.image_sizes.count # 1

# 已使用空间统计
user.space_size # 843367181

# 已使用空间统计，优化显示
user.space_size # "804.3MB"
···

**Comment by ben7th** [comment]
已经集成到 0.3 版。
