### ISSUE TITLE
图片测试方案

### ISSUE THREAD

**Issue by destinyd** [mindpin/image-service#22]
由于需要图片创建需要七牛请求才能实现。测试环境很难做到这一点。
所以需要制定一个方案用于图片测试（视频也可以参考）。

初始想法是这样：
1. 往项目测试路径**spec/photos/**里面添加两张图片。
2. 通过真实回掉，获取信息，通过factory_girl记录下。
3. 谁需要测试的时候，则将图片上传到自己的七牛bucket里面（固定名称），然后再进行测试即可。

**Comment by destinyd** [comment]
添加自动上传图片脚本，在七牛配置OK了的情况下执行：
```shell
rake uploader_test_files:images
```
测试即可正常运行

**Comment by ben7th** [comment]
已经集成到 0.3 版
