### ISSUE TITLE
第二轮需求整理

### ISSUE THREAD

**Issue by ben7th** [mindpin/image-service#7]
10月15日，img4ye 第一轮的网页版改版已经完成。目前的版本是1.0版

1.0版在原始版的基础上调整了网页视觉呈现，但没有增加什么特性。
2.0版本的计划是想把此服务由“团队内部使用”演化为“可以让更多人注册使用”

2.0版包括以下的原始需求（需细化）

- 用户可以使用新浪微博登录（暂时只提供这样一种登录模式，没有其他账号注册方法）。并且可以管理和外链自己账号下的图片。
- 每个用户的图片是不公开的。除非他把图片地址发给其他人，否则其他人是不会找到的。
- 2.0版会提供 chrome 插件。

- 匿名服务模式是否保留，需要进一步讨论。如果保留的话需要增加限制。

- 1.0版提出过，但是目前没有实现的一些特性：
    - 单个图片查看页用来获取特定尺寸的表单
    - 批量获取链接的操作

![](http://img.teamkn.com/i/UUjwt1ds.jpg)

**Comment by ben7th** [comment]
1. 针对每个用户，需要一个全局的尺寸配置。当用户在全局尺寸配置中添加了配置之后，上传的每一张图片，在图片详情页都会显示对应尺寸设置的URL等信息；

2. 图片张数统计，磁盘用量统计，自定义配置项统计放到首页的某个空白区域（例如右上角）

3. http://imgly.net/ 这个网站有一个体验是，批量图片的地址会显示在一个文本框里供用户选择

    ![](http://img.teamkn.com/i/HWDNMrGL.png)

    这样来复制地址可能会比较灵活。可以尝试调整一下目前的设计中复制链接的方式（目前的方式对于用户来可能有些隐蔽了）

4. 正在上传图片的列表和历史上已经上传的图片列表，从简化角度来说，可以放在一页。不过从减少视觉跳跃的角度来说，应该分成两个列表区域。

**Comment by chilliza** [comment]
Mockup下载地址：http://pan.baidu.com/s/1pJvAwcz

**Comment by ben7th** [comment]
mockup v2.1 参考地址（最新）
http://www.mindpin.com/mockups/img4ye/2014-4-9-v2-1/#p=structure

**Comment by ben7th** [comment]
已经集成完毕了
